### ISSUE TITLE
Kleisli::Try#to_either

### ISSUE THREAD

**Issue by maser** [txus/kleisli#12]
I’d like to do this:

```ruby
xml_string = "…"
Try {
  Nokogiri::XML(xml_string)
}.to_either >-> doc {
  text = doc.xpath
  if text
    Right(text)
  else
    Left("no text found")
  end
}
```

Would this even be a good idea? If you agree that it would be useful, I’ll implement it and send you a PR.

**Comment by abevoelker** [comment]
I'm curious about this also.  I have a method that either returns a Try or an Either similar to @maser's example; the happy path is simple since `.fmap` works the same for both, but in case of failure, the caller needs to know if they got a Left or a Try::Failure if they want to log what happened (to call `.left`/`.value` or `.exception`, respectively).  Unless I'm missing something obvious...

**Comment by txus** [comment]
Go for it! :D

**Comment by abevoelker** [comment]
Would be cool to see this merged - I've got a library that could benefit from this
